### ISSUE TITLE
decide on the R data structure for Demes models

### ISSUE THREAD

**Issue by grahamgower** [RacimoLab/demes-r#1]
E.g., could use the same nested lists data structure that is obtained just from loading the yaml file with the `yaml` library.
```R
> a = yaml.load_file("ex3.yaml")
> a
$time_units
[1] "generations"

$demes
$demes[[1]]
$demes[[1]]$name
[1] "A"

$demes[[1]]$epochs
$demes[[1]]$epochs[[1]]
$demes[[1]]$epochs[[1]]$start_size
[1] 1000
```

```
$ demes parse ex3.yaml > ex3_resolved.yaml
```

```R
> b = yaml.load_file("ex3_resolved.yaml")
> b
$description
[1] ""

$time_units
[1] "generations"

$generation_time
[1] 1

$doi
list()

$metadata
named list()

$demes
$demes[[1]]
$demes[[1]]$name
[1] "A"

$demes[[1]]$description
[1] ""

$demes[[1]]$start_time
[1] Inf

$demes[[1]]$ancestors
list()

$demes[[1]]$proportions
list()

$demes[[1]]$epochs
$demes[[1]]$epochs[[1]]
$demes[[1]]$epochs[[1]]$end_time
[1] 0

$demes[[1]]$epochs[[1]]$start_size
[1] 1000

$demes[[1]]$epochs[[1]]$end_size
[1] 1000

$demes[[1]]$epochs[[1]]$size_function
[1] "constant"

$demes[[1]]$epochs[[1]]$selfing_rate
[1] 0

$demes[[1]]$epochs[[1]]$cloning_rate
[1] 0





$migrations
list()

$pulses
list()
```

But probably it makes sense to use a `data.frame` for at least the `migrations`, `pulses`, `demes` and `epochs`.

**Comment by gregorgorjanc** [comment]
List is definitely the way to go I think, possibly even for the "data" part - we can easily index each node of a list, that is, there is not much difference between `df[row, col]` and `ls[[col]][row]` and internally data.frame is a list anyway.

**Comment by grahamgower** [comment]
Yeah, great. That was my initial thought - to make the internal format match what is obtained from the `yaml` library. But @reedacartwright suggested that `data.frame` might make sense too?

**Comment by gregorgorjanc** [comment]
Just to add that `df[[col]][row]` is a “list version” of doing `df[row, col]` to get a single value from a data.frame, hence having a list for everything (and use `ls[[col]][row]` everywhere?) would probably be the simplest approach. It is also what you get when you read in yaml in R.

Bit, maybe this should be also driven by use cases - what will be useful downstream?

**Comment by reedacartwright** [comment]
Representing data as `data.frames` would make it easier to use `dplyr` and other tidyverse-isms for manipulating the data. From the example above, I can see `$demes[[1]]$epochs` as something that could be stored as a data.frame.

**Comment by gregorgorjanc** [comment]
@reedacartwright that's correct. But maybe stating what functionality is needed ahead of making this decision would be the best approach in my view.

**Comment by grahamgower** [comment]
I'd love to have an idea of what sorts of data manipulations are likely to be useful to people!

**Comment by IsabelMarleen** [comment]
I definitely second your point @reedacartwright. Being able to use `tidyverse` extensions is certainly useful, especially if we want to enable visualisations and plotting downstream. I have not worked with Demes myself so I'm not sure what users normally use Demes and the corresponding software for and especially what might be useful for R users. So if any of you already have use cases or pipelines in mind that would be super useful to know.

**Comment by IsabelMarleen** [comment]
Thank you everyone for your input and suggestions. We have decided on a general data structure in R to represent Demes models and I'd appreciate concrete feature requests in separate issues. I will close this issue accordingly.
