### ISSUE TITLE
How can we get involved?

### ISSUE THREAD

**Issue by gregorgorjanc** [RacimoLab/demes-r#3]
How can we get involved? We would like to use R side for demes spec for our AlphaSimR calls of MaCS (https://github.com/gaynorr/AlphaSimR).

**Comment by grahamgower** [comment]
Hey @gregorgorjanc. Wow, you're quick, we only made this repository yesterday! Thanks for reaching out!

@IsabelMarleen is going to be working on creating this library as a student project over the next two months. Your input would certainly be valuable, particularly as a consumer of the library. I also have negligible R experience, so any feedback you can provide in respect of R specifics would be amazing. @bodkan has also kindly offered his guidance in this regard.

**Comment by gregorgorjanc** [comment]
I just by chance saw this repo mentioned when I opened GitHub yesterday and started following it;)

Happy to help on R side or testing things. Have wanted to dive into R side of demes, but didn’t have bandwidth, but given that we are contributing to stdpopsim it's a logical step to link all these things ups - one step at a time

**Comment by grahamgower** [comment]
It sounds like you'll want something like a Demes->MaCS translator too then? I guess you've already seen it, but demes-python includes converters to and from ms commands (both in the API and CLI). The ms->Demes conversion is actually pretty complicated (Demes->ms is not as bad), so there are no immediate plans to implement these for the R library too.

https://popsim-consortium.github.io/demes-docs/latest/api.html#conversion-functions

**Comment by gregorgorjanc** [comment]
I have opened an issue for Demes --> MaCS at https://github.com/popsim-consortium/demes-python/issues/487 (Python side). Let's work on that first and then the R side, I think.

@grahamgower shall we close this issue or keeping it open for others?

**Comment by gregorgorjanc** [comment]
A question - do you plan an R implementation from the ground-up or leveraging Python via reticulate?

**Comment by grahamgower** [comment]
It will be a relimplementation with minimal non-base dependencies. No Python/reticulate.

Feel free to close this issue. :)
